#!/usr/bin/env bash
# Pinging an IP address passed as an argument
# If no arg is passed, display:
#"Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"

if (( "$#"==0 ));
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
