#!/usr/bin/env bash
#Displaying "Best School" 10 times, for the 4th "bad luck"
#and the 8th "good luck"

i=1
while (( i < 11 ));
do
	if (( i == 4 ));
	then
		echo "bad luck"
	elif (( i == 8 ));
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
