#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with these requirement:
# localhost resolves to 127.0.0.2 AND facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "locahost 127.0.0.2" > ~/hosts.new
echo "facebook.com 8.8.8.8" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
